### ISSUE TITLE
Add next lesson button at bottom of each lesson for better experience

### ISSUE THREAD

**Issue by roberthopman** [doomspork/elixir-school#1085]
- [ ] Add next lesson button at bottom of each lesson

**Comment by eksperimental** [comment]
yes please.
not only next, but previous as well.

**Comment by sobering** [comment]
@doomspork, this enhancement was taken care of by @eksperimental in the most recently merged PR. This issue can be closed.

**Comment by doomspork** [comment]
Good catch @sobering!  Thanks again @eksperimental ❤️
