### ISSUE TITLE
Change the Norwegian language code

### ISSUE THREAD

**Issue by nscyclone** [doomspork/elixir-school#1090]
While trying to dig into pagination I ran into an issue with the Norwegian translation. Its language code is being interpreted as "false" according to the [yaml standard](http://yaml.org/type/bool.html).
There might be a plenty of workarounds but I thought that changing the language code might be the simplest one. The valid ISO 639 options are listed [here](https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes) (`nb`, `nob`, `nor`, `nn`, `nno`).

I am ready to propose a PR once we come up with a decision.

RFC @doomspork @robinsjdotcom @Devalo.

**Comment by eksperimental** [comment]
The language code is valid,
it's a bug in the yaml library then,
I don't know if you should change language codes for a website because a library doesn't recognize it.
Wikipedia does as in http://no.wikipedia.org

@nscyclone may I ask what is the issue you are having with the pagination?

**Comment by eksperimental** [comment]
I see the issue, it is being interpreted as `no` in english natural language.
Why not use "no" surrounded by quoted.

**Comment by nscyclone** [comment]
@eksperimental, as always everything genial is simple. It really worked, I've no idea how did I miss that option. Thanks a lot!
@doomspork I've just updated #1099. I guess now we don't need any other changes related to the Norwegian language code.

Anyway, all of this was not for nothing, we've discovered and utilized the redirect plugin to make the English lessons follow the common routing pattern.

**Comment by eksperimental** [comment]
No it was not. We need to move malaysian langugae. Im doing a big update to yhe will. Will push the PR later today

**Comment by eksperimental** [comment]
Big update To the site

**Comment by doomspork** [comment]
Thanks again for finding that plugin @eksperimental!  Do we need to keep this issue open or can we close it in favor of the others we have?

**Comment by eksperimental** [comment]
I think we can close it as this is solely related to the NO language. The Malaysian language issue has been opened.
