### ISSUE TITLE
Best Practices in Testing

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#118]
If there's no `Best Practices` content, why are we keeping this area in `testing.md` ? should we remove until someone send this data?

**Comment by doomspork** [comment]
That's a good point @pragmaticivan.  @pjhampton any thoughts on whether we should come up with some content or remove this?  If either of you have suggestions for topics I can sit down and work on it.

**Comment by pjhampton** [comment]
@pragmaticivan @doomspork let's remove it _for now_ and we'll come back to this later. I say this because we discussed adding Best Practices / FAQs at the end of each lesson.

**Comment by doomspork** [comment]
That sounds good to me.  Do either of you want to tackle removing it across the languages?  Please use a PR.

**Comment by pjhampton** [comment]
@doomspork @pragmaticivan On it! :smile:

**Comment by pragmaticivan** [comment]
I think we can close this one? right @doomspork ?

**Comment by doomspork** [comment]
Correct @pragmaticivan :+1:
