### ISSUE TITLE
Portuguese Translation: Advanced Lessons 🇧🇷

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#122]
- Advanced
 - [x]  concurrency.md 
 - [x]  erlang.md 
 - [x]  error-handling.md
 - [x]  escripts.md
 - [x]  metaprogramming.md 
 - [x]  otp-concurrency.md 
 - [x]  otp-supervisors.md
 - [x] umbrella-projects.md

**Comment by pragmaticivan** [comment]
@brunoasantos in case you want to pick any file, just comment here which one you're working with, so I can take another one.

**Comment by doomspork** [comment]
Teamwork :boom: 

Thank you guys for all your help, it's much appreciated.  Let me know if there's anything I can do to help.

**Comment by philss** [comment]
@pragmaticivan @brunoasantos @psantos10 I want to do the `Erlang Interoperability` translation. Is anyone working on this? May I start? Thanks!

**Comment by pragmaticivan** [comment]
@philss nop, just past here the file you're working with and new contributors will pick a different one.

**Comment by philss** [comment]
@pragmaticivan OK, thanks! I'm starting the `erlang.md` file.

**Comment by getbrandao** [comment]
@pragmaticivan I'm going to translate the concurrency.md file. It's ok?

**Comment by pragmaticivan** [comment]
Go for @getbrandao :) Let me know if you need any help

**Comment by pragmaticivan** [comment]
Solid week! we're almost there! Thank you all!
![runforrest](https://45.media.tumblr.com/tumblr_lzx3ahGwqm1qalcu6o1_r1_500.gif)

**Comment by ruan-brandao** [comment]
I'm starting the translation of `escripts.md` :smiley: 
OK?

**Comment by pragmaticivan** [comment]
Nice! @ruan-brandao go for!

**Comment by pragmaticivan** [comment]
Working on otp-supervisors.md.

**Comment by philss** [comment]
Starting the `otp-concurrency.md`.

**Comment by pragmaticivan** [comment]
:+1:

**Comment by DenysonSoares** [comment]
Starting error-handling.md, ok?

**Comment by pragmaticivan** [comment]
Cool @DenysonSoares , go for!

**Comment by pragmaticivan** [comment]
Starting `metaprogramming.md`.

**Comment by DenysonSoares** [comment]
Starting metaprogramming.md ok?

**Comment by pragmaticivan** [comment]
go for :)

**Comment by getbrandao** [comment]
I will take umbrella-projects.md, ok?

**Comment by pragmaticivan** [comment]
It's not ready yet @getbrandao . The project has a PR in #168

**Comment by getbrandao** [comment]
@pragmaticivan yep man, I see now when I was finding it.

**Comment by pjhampton** [comment]
@getbrandao I might need to make some minor changes so hold off for now man. :smile_cat: I will ping you when it's ready.

**Comment by doomspork** [comment]
@pjhampton I merged, sorry!  I didn't know you intended to make more changes.

**Comment by pjhampton** [comment]
@doomspork no, it's ok. I was referring to any potential late feedback. @getbrandao feel free to translate now if you want :+1:

**Comment by pragmaticivan** [comment]
Almost there! 🇧🇷
![e21537f3a9f36cfc6fb105ddf6afa564c86a3f72_hq](https://cloud.githubusercontent.com/assets/301291/13827073/ec91551e-eb77-11e5-94c5-82c5985757b9.gif)

**Comment by getbrandao** [comment]
@pjhampton thanks! I'm going to translate!

**Comment by DenysonSoares** [comment]
File metaprogramming delivered for approval.

**Comment by pragmaticivan** [comment]
100% o/
![anigif_enhanced-buzz-17101-1438254861-5](https://cloud.githubusercontent.com/assets/301291/13909954/249e2cb2-eed8-11e5-93db-255752b82cbe.gif)

Thank you all for the hard work!

**Comment by philss** [comment]
é nóis! Thank you! Congrats to the team!

**Comment by doomspork** [comment]
Nice job everyone! :tada: 

@philss & @getbrandao what are your twitter handles? :grinning:

**Comment by philss** [comment]
@doomspork it's [@philipsampaio](https://twitter.com/philipsampaio) o/

**Comment by getbrandao** [comment]
@doomspork and mine is [@getbrandao](https://twitter.com/@getbrandao)
