### ISSUE TITLE
Portuguese Translation: Specifics Lessons 🇧🇷

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#123]
- Specifics
 - [x]  ecto.md
 - [x]  eex.md
 - [x]  ets.md
 - [x]  mnesia.md
 - [x]  plug.md

**Comment by psantos10** [comment]
ecto.md translation in progress

**Comment by psantos10** [comment]
ecto.md translation in done!

eex.md translation in progress...

**Comment by pjhampton** [comment]
@psantos10 super thanks for these translations! You're awesome :smile: 

There was a _small but important change_ in the Mnesia (Specifics) lesson last night just incase you have copied any english files.

**Comment by pragmaticivan** [comment]
`mnesia.md` in progress.

**Comment by pragmaticivan** [comment]
@pjhampton Mnesia is updated and in Portuguese now. #done

**Comment by pjhampton** [comment]
Great job guys. Thanks very much

**Comment by pragmaticivan** [comment]
`plug.md` in progress.

**Comment by psantos10** [comment]
`ets.md` in progress

**Comment by pragmaticivan** [comment]
Done! o/

**Comment by doomspork** [comment]
:boom:  I'll get this tweeted out today.  Thank you everyone!  :+1:
