### ISSUE TITLE
Update text for function clause pinning in Translated Guides

### ISSUE THREAD

**Issue by jordan-brough** [doomspork/elixir-school#1368]
PR #1367 adds an extra note to the section on function clause pinning.

# Translation

Translation progress:

- [x] en
- [ ] ru /cc @brain-geek / @nscyclone
- [ ] ko /cc @devleoper
- [ ] jp /cc @3100
- [ ] no /cc @therobinsj
- [ ] pl /cc @Koziolek
- [ ] sk /cc @michalvalasek
- [x] fr /cc @julienXX
- [ ] cn /cc @cizixs
- [ ] es /cc @aleandros / @jonahoffline / @edwinallenz
- [ ] pt /cc @pragmaticivan
- [ ] vi /cc @joneslee85
- [ ] it /cc @lucidstack / @sformisano
- [ ] my /cc @alkaha
- [ ] id /cc @rezaprima

**Comment by eksperimental** [comment]
In my opinion should have updated the version number of the lesson. That way it would have been easier for translators to find out the new addition

**Comment by doomspork** [comment]
@eksperimental that's a good idea.  We can bump the lesson version
