### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#146]
- Just creating this issue here because the designers are new with github, so they have a place to comment.

**Comment by pjhampton** [comment]
Did we not already get a new logo? lol

**Comment by pragmaticivan** [comment]
The Elixir logo haev copyrights and plataformatec is taking so long to provide an answer. They are still talking with attorneys about that.

**Comment by pjhampton** [comment]
Hmm, that's annoying. Ok. I will hold off on adding it to the Elixir-Lang learning page until we have this sorted *just in case*.

**Comment by pragmaticivan** [comment]
[1] 
![logo1](https://cloud.githubusercontent.com/assets/301291/14766078/345aed30-09b2-11e6-9a74-4a163c00ccde.jpg)

**Comment by pragmaticivan** [comment]
[2]
![logo2](https://cloud.githubusercontent.com/assets/301291/14766079/3f4918d4-09b2-11e6-8f09-9cdd8bc06064.jpg)

**Comment by jeanleonino** [comment]
The `Elixir` word is hairline thin, that makes it hard to read sometimes. The second logo the drop is curved in a weird way on top:

![quirk](https://cloud.githubusercontent.com/assets/1311402/14771836/df5e7812-0a63-11e6-9404-0db838e7d3d5.png)

But the first one would be hard to see/understand in a small scale (like favicon). So both needs a bit of work :P 

PS: @josevalim, could Plataformatec have a public position about Elixir logo? That would make it easier for the community to interact.

**Comment by josevalim** [comment]
@jeanleonino our position today is public, it just isn't permissive: both Elixir logo and brand are copyright to Plataformatec and cannot be used without permission.

The annoying part is that we mostly cannot grant any kind of permission until the bureaucratic process is done.

**Comment by doomspork** [comment]
Thanks for the explanation @josevalim 😀

**Comment by pragmaticivan** [comment]
cc @doomspork any feedback about what should be do here?

**Comment by pragmaticivan** [comment]
![elixir-school-logo-final](https://cloud.githubusercontent.com/assets/301291/15170037/cf6dc62a-16f6-11e6-91e9-4dc059419c32.png)

**Comment by pragmaticivan** [comment]
Does anyone have any new feedback? Those logos have been waiting here for 18 days.

**Comment by pragmaticivan** [comment]
cc @doomspork @pjhampton

**Comment by pjhampton** [comment]
I like it @pragmaticivan, it's my favorite... but it's not my decision sadly. @doomspork do you have an update on the logos?

**Comment by doomspork** [comment]
@pjhampton as I said to @pragmaticivan in the channel, we are going with his logo.  This is an opportunity for someone to offer feedback on improving the final draft.

Let me just set some expectations while we're here.  I cannot convey enough how much I appreciate all of the help with this project but please be reasonable with when you expect responses.  We've just had a long discussion about this and it's only been 2 days, I work a full time job, and there's many other things going on with this project and others.  It may take me a few days to get back to you.  Please be patient.

**Comment by pragmaticivan** [comment]
Hey thanks for the feedback, actually I posted asking for general feedback and marked you guys after to keep tracking haha. That makes sense, not in a hurry just wanted to leave a comment after the logo update.

**Comment by doomspork** [comment]
I'm sitting down today to give this the time it deserves.  Thanks for the patience @pragmaticivan 👍

**Comment by doomspork** [comment]
Okay!  First and foremost, this is an _awesome_ idea and I greatly appreciate your help @pragmaticivan.  That said, here is the little feedback I do have:

- The school doesn't appear to be centered.  If you look at the stairs you can see he horizon enters and exits at different heights which suggests it's off center.
- The Elixir logo/icon/mark does not have smooth lines.  I worry that will be more apparent if it was printed.
- Lines of the school aren't as sharp as the rest of the image, I'm not sure how well that will print.

I asked a designer friend of mine to take a look at it if he had some time, I haven't heard back from him.  One piece of advice he did have was to use vector graphics if possible, that would insure it printed correctly.

**Comment by doomspork** [comment]
Closing this for now, got some things in the works 😀
