### ISSUE TITLE
Posssible Typo in Sigils

### ISSUE THREAD

**Issue by joeltrew** [doomspork/elixir-school#181]
Under the regular expressions part it says "Because Elixir supports Perl Compatible Regular Expressions (PCRE), we can append i to the end of our sigil to turn on case sensitivity." 
however the example shows this turns **off** case sensitivity, and makes the regular expression insensitive to case

**Comment by pjhampton** [comment]
Hey Joel, 

You are correct. Would you like to the submit the PR or do you want to leave it with me?

Thanks

**Comment by joeltrew** [comment]
I'll submit a PR now (I've never done this before so bear with me!)

**Comment by pjhampton** [comment]
@joeltrew no problem. Let me know if you need / want any guidance. I will be happy to help :+1:
