### ISSUE TITLE
Create a lesson about Strings

### ISSUE THREAD

**Issue by setzer777** [doomspork/elixir-school#186]
Suggesting to create a lesson about Strings in Elixir, starting from: 
1. how do they work
2. simple operations and manipulation
3. how are they handled inside the BEAM
4. Etc.

If you need some help with that, please let me know! :smile:

**Comment by pjhampton** [comment]
Great idea, @setzer777! And thanks for the suggestion. 

I am currently working on an Elixir Natural Language Processing library as part of my PhD (it's currently private on my github) and I have been looking into this for quite sometime. 

Maybe we could work together on this lesson together?

**Comment by setzer777** [comment]
Great @pjhampton! I bet functional programming have helped you a lot with your project :stuck_out_tongue: 

Of course! Let's just split the lesson into sections and then we can start to work :)

**Comment by doomspork** [comment]
:boom: Teamwork ftw!

**Comment by setzer777** [comment]
I propose this sections for the lesson:

1.  Strings in Elixir: Explain what's the deal with strings in Elixir, about their binary-ty and stuff haha
  - Graphemes
  - Codepoints
2.  Common functions:
  - downcase/uppercase
  - length
  - split
  - at
  - contains
  - to_char_list (this is gonna be interesting...)
3.  String manipulation
  - iterate a string
  - replace characters

I just have this at the moment, let's fulfill the lesson! :)

**Comment by pjhampton** [comment]
Supercool @setzer777!!

Do you have Slack? If not sign up here: https://elixir-slackin.herokuapp.com/

We have our own channel **#elixirschool** where we can chat about this further :smile_cat:

**Comment by nscyclone** [comment]
PR #224 was merged today. I think this issue can be closed now.
