### ISSUE TITLE
Add some exercises at the end of each lesson!

### ISSUE THREAD

**Issue by setzer777** [doomspork/elixir-school#187]
Another suggestion is to add some exercises at the end of the modules, so ElixirSchool can turn into a real school where people (or maybe a machine) is evaluating the students work c: I'd also be glad to help you on that.

There could be many ways to accomplish this:

1. We put an exercise and the answer is sent via email to someone to check it.
2. We (somehow) evaluate the code inside an interpreter and check the result.

The easiest way in my opinion to put some exercises is to create some mix projects inside an exercises repo, make some tests inside the mix projects and make the students to make the tests pass writing the answer code into the lib folder.

What do you think fellas? :shipit:

**Comment by doomspork** [comment]
@setzer777 this is a good idea, I think this would be a good addition.  Let's dig in further and see what makes the most sense.

**Comment by setzer777** [comment]
Thoughts on this:

1. After each lesson, provide a simple solved exercise that uses the topics reviewed on the lesson.
2. After the solved exercise, provide a new unsolved exercise with some hints!

I think the best approach is to make them clone a repo with projects made with mix, add the problems ordered by lessons, and just include the tests in the projects, so they can run `mix test` and make all the tests pass.

Any thoughts on this? @doomspork @pjhampton

**Comment by pjhampton** [comment]
@setzer777 @doomspork 

Let's continue this discussion on Elixir Slack - #elixirschool

**Comment by doomspork** [comment]
I think we've agreed this is something we're interested in doing so I'm going to close this issue for the time being.  Let's open separate issues for incorporating the exercises 👍
