### ISSUE TITLE
Add share buttons to lessons footer.

### ISSUE THREAD

**Issue by pjhampton** [doomspork/elixir-school#199]
It would be great to introduce a new feature which allows a user to share a lesson over different social networks from the bottom of a lesson. It would maybe look like something like the attached image but horizontal.

![screen shot 2016-03-23 at 17 29 49](https://cloud.githubusercontent.com/assets/8960296/13994534/22fce582-f11d-11e5-9821-0e1834bd2296.png)

**Comment by pragmaticivan** [comment]
I agree with this one, very nice feature and would help to spread the website in the web.

**Comment by setzer777** [comment]
I also agree :) besides it's not complicated.

**Comment by pjhampton** [comment]
Sure, I agree. Let's see if a new person would like to tackle it in the next couple of days. If not, it's up for grabs!

**Comment by doomspork** [comment]
This will be _great_, good idea :+1:

**Comment by veverkap** [comment]
What services should be included?  YouTube/Instagram are probably not ideal.

- Facebook
- Twitter 
- LinkedIn
- Reddit
- HackerNews
- Google+
- Pocket?
- Email
- Pinterest?
- Tumblr?

Using something like https://github.com/kni-labs/rrssb would be nice too.

**Comment by doomspork** [comment]
Good question @veverkap.  Initial I was thinking about just FB, Twitter, and Reddit.  Now that you mention it, Email, HN, and Google+ might be good additions too.

I like rrssb :+1: 

Thoughts?

**Comment by veverkap** [comment]
![image](https://cloud.githubusercontent.com/assets/22348/14294506/8f49aa50-fb3f-11e5-9d2d-a97798ec3787.png)

So far, not so good with the default implementation.

**Comment by veverkap** [comment]
Progress:

![image](https://cloud.githubusercontent.com/assets/22348/14304770/d35d732c-fb83-11e5-99f9-f296ac976db9.png)

**Comment by doomspork** [comment]
This was done as part of #260 but there is an issue with the fonts.  Once we get the fonts self hosted we can close this.

**Comment by doomspork** [comment]
This should be fixed thanks to #288 and @burden's help.
