### ISSUE TITLE
Polish Translations

### ISSUE THREAD

**Issue by pjhampton** [doomspork/elixir-school#202]
## Get Involved!

We are seeking **Polish** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.

- **Set up**
  - [x] _config.yml
  - [x] index.md 

- **Basics**
  - [x] Collections
  - [x] Enum
  - [x] Pattern Matching
  - [x] Control Structures
  - [x] Pipe Operator
  - [x] Functions
  - [x] Composition
  - [x] Mix
  - [x] Sigils
  - [x] Documentation
  - [x] Testing
  - [x] Comprehensions
  - [x] Strings
  - [x] Custom Mix Tasks

- **Advanced**
  - [x] concurrency.md
  - [x] errors.md
  - [x] erlang.md
  - [x] escripts.md
  - [x] otp-concurrency.md
  - [x] otp-supervisors.md
  - [x] metaprogramming.md
  - [x] umbrella projects.md

- **Specifics**
 - [x]  ecto.md
 - [x]  eex.md
 - [x]  ets.md
 - [x]  mnesia.md
 - [x]  plug.md

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by Koziolek** [comment]
I could do part of this.

**Comment by Koziolek** [comment]
Forked to https://github.com/Koziolek/elixir-school branch issue-202
If anyone else would like to help please send me message we will coordinate our work

**Comment by pjhampton** [comment]
Yep, sounds good @Koziolek! You lead this and we will send out a contributors later!

Thanks :smile:

**Comment by doomspork** [comment]
That is great news @Koziolek!  @kdebowski already opened our first Polish PR if you want to take a peek at it: #271

**Comment by kdebowski** [comment]
@Koziolek, I've already started translating files to polish language. Files are divided into chapters and I'm in the beginning os basics.md - you can easily pick some file from the rest if you want to evade potential conflicts

**Comment by Koziolek** [comment]
@kdebowski 
Basics done ;) we need to coordinate it. Do you have trello account to coordinate translation (and make subtrasks list)?
Now I start to translate eex.md from special

**Comment by kdebowski** [comment]
@Koziolek I've created Trello board for polish translations. If you could provide me your email account for Trello I can add you as a member.

**Comment by doomspork** [comment]
@kdebowski and @Koziolek, what are you twitter handles? 😀

**Comment by Koziolek** [comment]
koziolek 
https://twitter.com/koziolek

**Comment by kdebowski** [comment]
https://twitter.com/kamil_debowski

**Comment by doomspork** [comment]
@kdebowski or @Koziolek, would one of you like to lead the Polish translations?  I can add you to the repo so you can manage the issue and merges.  The only request is that you refrain from pushing to master and rely on pull requests so other contributors have an opportunity to provide feedback.

**Comment by Koziolek** [comment]
Sounds good for me. It makes our work faster.

**Comment by doomspork** [comment]
@Koziolek I've added you as a collaborator so you can update this issue and merge PRs.  Please squash commits if there are many per lesson 👍 

Myself and the other contributors are on Slack in the #elixirschool channel, if you'd like to join us 😀

**Comment by Koziolek** [comment]
@doomspork could you close this :)
