### ISSUE TITLE
Ignore Ruby Version and Gemset for RVM

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#226]
I found this commented in `.gitignore`. Can I ignore those files? I like to keep my local env organized.

```
# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset
```

**Comment by pjhampton** [comment]
Makes no difference to me. @doomspork?

**Comment by doomspork** [comment]
Open a PR :+1:

**Comment by setzer777** [comment]
I don't fully understand this issue. Wouldn't it be better if just you uncomment those files in your local without affecting the whole repo? Or is it a real need for the repo? :shipit:

**Comment by doomspork** [comment]
@setzer777 you make a good point.  It's certainly not a repo need, though I am willing to consider small changes that make it easier for contributors.  Do you have concerns?

**Comment by setzer777** [comment]
@doomspork Small changes in the .gitignore? or which kind of changes?

**Comment by doomspork** [comment]
@setzer777 adding `.ruby-version` and `.ruby-gemset` (__not__ `Gemfile.lock`).  Many Ruby developers rely on them and they're not included in this project.  I suspect for folks like @pragmaticivan it's annoying having to remember to not commit those files.

**Comment by doomspork** [comment]
Going to close this.  @pragmaticivan feel free to open a PR for further discussion.

Thanks!
