### ISSUE TITLE
Configure Open Source version of Teatro.IO

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#227]
Here's the service: https://teatro.io/

It will help us to QA with a staging environment for each Pull Request.

**Comment by pjhampton** [comment]
![](http://i62.tinypic.com/2802hxt.jpg)

**Comment by setzer777** [comment]
That looks super cool! :D

**Comment by doomspork** [comment]
I signed up and enabled it for Elixir School.

**Comment by doomspork** [comment]
I'm going to close this for now.  We'll focus on using Heroku's pipeline and Review Apps for the time being.
