### ISSUE TITLE
Content in sidebar is hidden

### ISSUE THREAD

**Issue by asarode** [doomspork/elixir-school#23]
Looks like you've got a lot of lessons now! The sidebar hides the content for me and I'm not able to scroll.  I'm sending along a pull request to fix the issue.

<img width="509" alt="sidebar content hidden" src="https://cloud.githubusercontent.com/assets/4860899/11452314/0e1efbfc-95a9-11e5-88e7-eb2c51528493.png">

**Comment by doomspork** [comment]
Closed via #24.

Thanks again @asarode :+1:
