### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by erickgnavar** [doomspork/elixir-school#25]
Hi, I would like to contribute to translate the repo to spanish, could you guide me how to proceed?

Thanks

**Comment by doomspork** [comment]
Whoa!  @erickgnavar that would be __awesome__!  I'm not entirely sure how we'd go about doing that but I will make it a priority this week to investigate.

**Comment by ZuraGuerra** [comment]
Hi! I'd like to help translating too. :)

**Comment by doomspork** [comment]
@erickgnavar & @ZuraGuerra thanks again for your offer!  

I was looking into our options for Jekyll and found [this blog post](http://brendamour.net/en/2014/08/03/multilingual-jekyll-how-to-post-in-more-than-one-language/).  I like the approach outlined as opposed to the traditional i8ln language files.  Do either of you have any thoughts?

Super excited to get this kicked off.  Thanks again :+1:

**Comment by 3100** [comment]
Hi, I'm translating this site into Japanese at repos https://github.com/3100/elixir-school and its url is https://3100.github.io/elixir-school . It may be easier to build each languages' website as github project pages if you don't care its url, though it will need some changes to work with subdirectory. (See my [branch](https://github.com/3100/elixir-school/commits/japanese) for more detail.)

Of cource, I think i18nise is a good way, too.

**Comment by doomspork** [comment]
@3100 that's awesome!  It's great to hear other people are using/enjoying/contributing! 

I _think_ it's best to keep all of the content together in the same repo.  Then we can maximize everyone's efforts and keep lessons in-sync easier.  I've got time this week so I'm going to look into ways to handle hosting these different translations on elixirschool.com (and Jekyll).

This is really exciting!

**Comment by erickgnavar** [comment]
I don't have experience with Jekyll but I think is better have all the translations in the same repo, the files can be separate by folders per language (like the [Django Girls tutorial](https://github.com/djangogirls/tutorial)) or follow the the tutorial.

**Comment by ZuraGuerra** [comment]
I haven't used Jekyll either, do you suggest any reading aside from the docs? I also think it would be better to have every language under the same repo.

I checked @doomspork link and according to it (please, correct me if I got it wrong) we could add the posts to language folders under lessons/advanced, lessons/basics and lessons/specifics.

**Comment by doomspork** [comment]
Alright!  I was able to make some progress this evening on setting up multi-language support.  I'm going to clean it up a bit more and then push a PR for review.

Here it is in action:

![multi-lang](https://cloud.githubusercontent.com/assets/73386/11580265/48d6d61c-99ea-11e5-8e5b-4181009b5ce6.gif)

**Comment by doomspork** [comment]
Support for translations has been merged! :tada: 

Any suggestions on how about managing this?  Should we create GitHub issues for each language and lesson?  I'd be glad to add active contributors to the repo to speed things up.

**Comment by erickgnavar** [comment]
Awesome, I think that creating a issue per language and lesson is a good idea, I have a few translated lessons I'll make a PR tomorrow.
Again, great work 👍

**Comment by 3100** [comment]
Great :tada:

**Comment by ZuraGuerra** [comment]
@erickgnavar, on which lessons are you working? If you are translating Basics, I can start with the Advanced section tomorrow.

**Comment by erickgnavar** [comment]
Yes, I'm working on basic lessons.

**Comment by ZuraGuerra** [comment]
Nice!

**Comment by doomspork** [comment]
@erickgnavar & @ZuraGuerra I'm going to close this issue now that we've sorted out the translation stuff.  

I created three separate issues for the actual translations.  Let me know your thoughts:

#37 — Spanish Basic Lessons
#38 — Spanish Advanced Lessons
#39 — Spanish Specific Lessons

**Comment by ZuraGuerra** [comment]
That's perfect!
