### ISSUE TITLE
Missing Supervisor code on Ecto migrations example 

### ISSUE THREAD

**Issue by luizvarela** [doomspork/elixir-school#27]
In the chapter about `Ecto`, specifically in `Migration` topic, I think that you miss explaining the `Supervisor` part. When we generate an `mix` application without `--sup`  we don't get the `Supervisor` code and we must put it manually and if you try to run the migrations the code doesn't run.

https://github.com/elixir-lang/ecto/blob/master/examples/simple/lib/simple.ex#L4

Maybe you skipped this part but I think that is important to show :)

**Comment by doomspork** [comment]
Thanks for pointing that out @luizvarela, I agree it's important.  I'm working on some new lessons and updates to others, I'll add this to the list.

Thanks again :+1:

**Comment by luizvarela** [comment]
That's great @doomspork, I can help you with some reviews. :smile:

**Comment by doomspork** [comment]
That'd be great!  I'll tag you in a PR later today.  Thanks for your help @luizvarela.
