### ISSUE TITLE
Remove Line of available languages from index of all languages but english

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#270]
`Available in Việt ngữ, 汉语, Español, 日本語 and Português.`

It's creating complexity to update that every time a new language comes to the website.

Now we have `en jp cn es pt vi ru sk fr gr it` and it doesn't represents the list in the index.

My suggestion is to have this `Available in Việt ngữ, 汉语, Español, 日本語 and Português.` in the english version.

**Comment by doomspork** [comment]
Thoughts @jesusangelm / @joneslee85 / @setzer777  / @brain-geek and others?
