### ISSUE TITLE
Upgrade Elixir version in examples?

### ISSUE THREAD

**Issue by AquarHEAD** [doomspork/elixir-school#275]
For example in [Basic](https://elixirschool.com/lessons/basics/basics/), the first code example is 2 minor version behind latest Elixir version.

```
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex>
```

**Comment by doomspork** [comment]
@AquarHEAD can you take the lead on updating all of the examples?  One PR should be sufficient for all of the changes.

**Comment by AquarHEAD** [comment]
@doomspork Sure will do as soon as I find enough time to go over everything :)

**Comment by doomspork** [comment]
Great!  Thank you @AquarHEAD

**Comment by nscyclone** [comment]
Dear @AquarHEAD, you were gone for a long time, so I made a PR for this issue on my own: #321. I hope I didn't have done any harm by this.

**Comment by AquarHEAD** [comment]
@nscyclone Thanks, was on a business trip last 2 weeks, and now just started a vacation, so barely have time to do things on my own( I'm happy that someone else could help, that's part of the reason why I opened an issue first :D

**Comment by doomspork** [comment]
Thank you @AquarHEAD and @nscyclone 👍
