### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by jakefolio** [doomspork/elixir-school#281]
I just wanted to point out a few things I noticed while reading the site:

1. Default link color is the same as text and doesn't have an underline to make it obvious it's a link
2. The site name/logo links to the current page and doesn't bring you back to the homepage.

**Comment by doomspork** [comment]
Hi @jakefolio, thanks for the feedback!  Would you open to contributing fixes for these?  PRs are welcome :grinning:

**Comment by doomspork** [comment]
Closed via #282, thanks again @jakefolio :+1:
