### ISSUE TITLE
Basic menu section is always open

### ISSUE THREAD

**Issue by eksperimental** [doomspork/elixir-school#314]
Regardless if you are reading an article in the other sections.

Browser: Chrome and Firefox
OS: Linux

**Comment by doomspork** [comment]
Thanks for the report @eksperimental!

**Comment by nscyclone** [comment]
I'm going to fix this within the next few days.

**Comment by doomspork** [comment]
Thank you @nscyclone, that'd be great!

**Comment by doomspork** [comment]
Fixed by @nscyclone in #330
