### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by 3100** [doomspork/elixir-school#33]
Here I will create translated files; any advice, reviews and/or tips are welcome:

- [x] index.md
- Basic
  - [x] basics.md
  - [x] collections.md
  - [x] composition.md
  - [x] control-structures.md
  - [x] enum.md
  - [x] functions.md
  - [x] mix.md
  - [x] pattern-matching.md
  - [x] testing.md
- Advanced
  - [x] concurrency.md
  - [x] erlang.md
  - [x] escripts.md
  - [x] otp-concurrency.md
  - [x] otp-supervisors.md
- Specifics
  - [x] ecto.md
  - [x] plug.md
- [x] Modify internal links of each TOB

**Comment by doomspork** [comment]
Awesome work @3100!

**Comment by doomspork** [comment]
Closed via #35.  Thanks again @3100 :+1:
