### ISSUE TITLE
Lesson about custom types and @spec

### ISSUE THREAD

**Issue by Koziolek** [doomspork/elixir-school#338]
Probably basic, but I'm not sure. 

Short summary:
- the `@spec` and how to define "interfaces"
- Creating custom types
  - Why we need it - tuples are too generic 
  - `@type` and how to use it
  - short exercise - create custom type of email that will be keyword of `[{:name NAME}, {:domain, DOMAIN}]` with set of functions like `toEmail` and `fromEmail`. 

@doomspork @pjhampton any suggestions?

**Comment by doomspork** [comment]
I've wanted to do a typespec lesson for awhile!  I think this is a good idea.

**Comment by pjhampton** [comment]
Yep. I also love this idea. Do you want me to write this lesson or do you want to take it @Koziolek?

**Comment by Koziolek** [comment]
I'm writing this. Should be ready to review in next few days.

**Comment by doomspork** [comment]
Awesome @Koziolek!  Looking forward to it.

**Comment by Koziolek** [comment]
In https://github.com/doomspork/elixir-school/pull/564

@doomspork, @nscyclone  guys, could you take a look and put your comments.

**Comment by doomspork** [comment]
Thank you @Koziolek, I will look today 👍

**Comment by pjhampton** [comment]
I like this @Koziolek. Once we firm up the semantics, I will help you fine tune the English. Thanks for contributing as usual ❤️

**Comment by nscyclone** [comment]
Closing this one because the original lesson is already merged (#564) and the translation task list is in another issue (#850).
