### ISSUE TITLE
Spanish Translation: Basic Lessons

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#37]
- [x] index.md
- Basics
  - [x] basics.md
  - [x] collections.md
  - [x] enum.md
  - [x] pattern-matching.md
  - [x] control structures.md
  - [x] functions.md
  - [x] composition.md
  - [x] mix.md
  - [x] testing.md

**Comment by erickgnavar** [comment]
Hi @doomspork, I'm working in this section could you assign me this issue for update its status?

**Comment by doomspork** [comment]
Sure @erickgnavar, I can do that tonight.  I'll add you to as a collaborator on the repo.  Please stick to PRs for major changes :+1:

**Comment by doomspork** [comment]
@erickgnavar you've been added to the project.  Thanks again for your help :grinning:

**Comment by erickgnavar** [comment]
Thanks :+1:

**Comment by doomspork** [comment]
Thank __you__ for your help with these translations.

**Comment by roadev** [comment]
I'm helping to fix some grammatical errors (some: "tildes" and typo errors).

**Comment by doomspork** [comment]
Thank you @roadev!

**Comment by setzer777** [comment]
Hi guys! I'm also interested in contribute to the translation! Are composition and testing lessons still pending to translate? :shipit:

**Comment by doomspork** [comment]
@setzer777 I do believe so!  Thanks for your interest

**Comment by setzer777** [comment]
Great! I think I'll start with composition lesson right now! I'm excited to help you out guys! I have already forked the repo :)

**Comment by setzer777** [comment]
Composition translation in PR [#185](https://github.com/doomspork/elixir-school/pull/185)

**Comment by setzer777** [comment]
I'd suggest to change the translation "Coindidencia de patrones" to "Pattern Matching" itself, I think we don't have to translate everything if we don't want to turn things more complicated, so users can search the term itself and find more information about it, instead of figuring out how to backward-translate the term.

Just a humble suggestion :shipit:

**Comment by Gidrek** [comment]
I am agree with @setzer777 about pattern matching

**Comment by erickgnavar** [comment]
Yep, I agree too, we don't have(still) a glossary to manage this.

**Comment by setzer777** [comment]
Yeah, the problem is that the word "Coincidencia" is used like a lot. The solution would be to use the word "match" instead, but it'll make the text super spanglish XD @erickgnavar @Gidrek

**Comment by doomspork** [comment]
@setzer777 @erickgnavar and @Gidrek I'd love to get your thoughts on a Glossary, mind commenting on PR #162?

**Comment by doomspork** [comment]
@erickgnavar with your `testing.md` PR, does that complete this list?

**Comment by erickgnavar** [comment]
Yes, 😀

**Comment by doomspork** [comment]
:boom:  I'll send out a tweet later today about this milestone.

Thanks everyone!
