### ISSUE TITLE
Spanish Translation: Specific Lessons

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#39]
- Specifics
  - [x] ecto.md
  - [x] plug.md
  - [x] ets.md
  - [x] eex.md

**Comment by milmazz** [comment]
@doomspork Is somebody working on this right now?

**Comment by doomspork** [comment]
Hi @milmazz, I don't think so.  @erickgnavar is leading the charge on the Spanish translations so he'd be the best person to ask :grinning: 

Thank you for your interest & Happy Holidays!

**Comment by milmazz** [comment]
@doomspork @erickgnavar Great! working on `ecto.md` right now.

**Comment by doomspork** [comment]
Awesome @milmazz, thanks for your help.

**Comment by erickgnavar** [comment]
@milmazz :+1:

**Comment by milmazz** [comment]
@doomspork Please check the `EEx`, it's already done.

**Comment by doomspork** [comment]
@milmazz done!  You should now be able to toggle those checkboxes :+1:

**Comment by doomspork** [comment]
This is now done!  :tada: 

Thanks @milmazz, @jesusangelm, and @erickgnavar :+1:
