### ISSUE TITLE
Mistake in Advanced/Executables lesson in an example

### ISSUE THREAD

**Issue by setzer777** [doomspork/elixir-school#392]
![image](https://cloud.githubusercontent.com/assets/13922607/15457365/81fe23b6-204d-11e6-87a8-a6873eb5ebf2.png)

The upcase from hello is not WORLD, but in fact, HELLO.

**Comment by doomspork** [comment]
@setzer777 could you open a PR to fix this?

**Comment by aleandros** [comment]
@setzer777 @doomspork I think this is not a mistake. I copy my response from the PR discussion:


```elixir
  defp response({opts, "Hello"}), do: response({opts, "World"})
  defp response({opts, word}) do
    if opts[:upcase], do: word = String.upcase(word)
    word
  end
```

So `response({[upcase: true], "Hello" })` would expand to `response({[upcase: true], "World"})` which would then be "WORLD"

**Comment by aleandros** [comment]
The example is a little bit misleading though. While correct, this discussion might mean that the example adds unnecessary complexity for the subject at hand. An option would be to open a PR to completely remove the first clause definition for `response/1` and change the corresponding example.

**Comment by doomspork** [comment]
@aleandros you are correct, this isn't a bug after all.  You may be correct about the confusion as well.  @setzer777 what do you think?

**Comment by setzer777** [comment]
Oh yeah I got it! I didn't see the code at the moment, but I fully agree with aleandros
So, the TODOs are:
1. Remove the useless function option:
```ex
 defp response({opts, "Hello"}), do: response({opts, "World"})
```
2. Fix the output described in this issue.

**Comment by doomspork** [comment]
This is now resolved.
