### ISSUE TITLE
Lesson Suggestions

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#50]
This can serve as a place for folks to suggest new lessons.  

Suggested lessons:

**Advanced:**
- [ ] OTP Architecture
- [ ] Distribution
- [ ] GenStage

**Specifics:**
- [ ] Creating a DSL
- [ ] Leex & Yecc
- [ ] Dialyzer / Debugging (created #566 )
- [ ] Hex Docs

**Libraries:**
- [ ] Guardian (in-progress #431)
- [ ] exrm 
- [ ] Bamboo

**Comment by doomspork** [comment]
Two additional lesson that could either be lessons or just a section in another lesson: sigils and comprehensions

**Comment by pjhampton** [comment]
Do you mean a lesson on existing sigils or creating custom sigils?

**Comment by doomspork** [comment]
I would like to cover both topics actually!  They could certainly be in the same lesson.

**Comment by pjhampton** [comment]
Ok, cool. I can certainly try and tackle this one!

**Comment by doomspork** [comment]
That's great! 

@pjhampton as I've done with other contributors I'll add you to the repo so you can assign issues to yourself and update them.  I do ask that big changes go in via PR so they can be reviewed and we can ping folks doing translations.  Sound good?

Master is deployed on merge.

**Comment by pjhampton** [comment]
Sounds good! I will get started with Sigils this week coming.

**Comment by doomspork** [comment]
I started on "Creating a DSL" lesson but I'm not entirely sure _what_ DSL to build.  Most of the existing examples create new types of assertions but I'd like to do something different.  Any thoughts @pjhampton?

**Comment by pjhampton** [comment]
@doomspork I will get back to you on this once I have done some thinking.

**Comment by doomspork** [comment]
Go for it @pjhampton :grinning:

**Comment by pragmaticivan** [comment]
Are `nodes` inside `Distribution`? Should we have a lesson just for `nodes`? I think it's a good one to have after processes.

**Comment by pjhampton** [comment]
Hey @pragmaticivan. Nodes were mentioned in `Mnesia` which I wasn't happy about, but I needed to give context as it is a distributed database. But yeah, from what knowledge I have, nodes fall under distribution.

**Comment by doomspork** [comment]
I'm going to close this issue in favor of conversations we have in Slack.

**Comment by ybur-yug** [comment]
@doomspork do you want to reopen this per our discussion earlier today or should I just join the slack group?

**Comment by doomspork** [comment]
I will re-open today when I'm back home 👍

**Comment by ybur-yug** [comment]
Cool. Can't wait to do some real contribution! If you'd like shoot me a DM on Slack when you have some time to chat, I'd like to run something by you that this could definitely be incorporated into :)

**Comment by doomspork** [comment]
Updated this with a few new lessons, open to suggestions for others!

**Comment by ybur-yug** [comment]
@doomspork hex docs & creating a DSL I'd love to do. Could probably knock out one of them this weekend.

I'm also doing some personal work with GenStage but I lack the expertise to do a writeup that gives the module justice yet. But hopefully I get there in hte coming weeks.

**Comment by ybur-yug** [comment]
@doomspork also just noticed you were talking about wanting to the DSL bit but its from quite a while ago. I was thinking of making a simple one that translates to markdown or something. Or maybe if I wanted to be really cool LaTex or something, but thats totally a large yak to shave. Thoughts?
