### ISSUE TITLE
Incorporate Elixir 1.2 changes into lessons

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#52]
Elixir 1.2 introduced a number of changes we should incorporate into lessons:

  * The addition of multi aliases/imports/require:

        alias MyApp.{Foo, Bar, Baz}

  * Support for variables in map keys:

        %{key => value}

  * Support for the pin operator in map keys and function clauses:

        %{^key => value} = %{key => value}
        fn ^key -> :ok end

  * Addition of the `with` special form to match on multiple expressions:

        with {:ok, contents} <- File.read("my_file.ex"),
             {res, binding} <- Code.eval_string(contents),
             do: {:ok, res}

**Comment by pjhampton** [comment]
Hey @doomspork, 

Maybe worth considering the removal of `Dict` as well from [collections](http://elixirschool.com/lessons/basics/collections/#dicts) as they have been *softly deprecated* as of [Elixir v1.2](http://elixir-lang.org/docs/v1.2/elixir/Dict.html). This is also the case for HashDict but I didn't come across any material on Elixir School.

**Comment by doomspork** [comment]
Great point :+1:
