### ISSUE TITLE
Liquid template variables {{ }} conflict with code blocks

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#55]
Liquid assumes all uses of `{{ }}` are for variables, even inside code blocks.  This became apparent when the ETS lesson was deployed:

```
Liquid Exception: Liquid syntax error: Variable '{{:"$1", :"_", :"$3"}' was not properly terminated with regexp: /\}\}/ in lessons/specifics/ets.md
```

Temporary workaround is to add a space: `{ {:"$1", :"_", :"$3"}`.  Gotta find a better solution.

**Comment by milmazz** [comment]
@doomspork You can use `{% raw %} .. `{% endraw %}` block, which you can temporarily disables tag processing. I'll fix that in a moment.
