### ISSUE TITLE
Lesson about Dialyzer, Dialyxir and debugging

### ISSUE THREAD

**Issue by Koziolek** [doomspork/elixir-school#566]
Based on experience with #338 and list from #50.
1. Create lesson in Specifics group
2. Check lesson about spec and add links

**Comment by Koziolek** [comment]
Advanced or Specifics this is the Question?

IMO Specifics, @doomspork, @nscyclone, what do you think?

**Comment by doomspork** [comment]
👍 for Specifics

**Comment by nscyclone** [comment]
Closing this one because the original lesson is already merged (#900)  and the translation task list is in another issue (#921).
