### ISSUE TITLE
Description of @doc also uses @spec without describing it

### ISSUE THREAD

**Issue by scouten** [doomspork/elixir-school#590]
In http://elixirschool.com/lessons/basics/documentation/#documenting-functions, you introduce the concept of the `@doc` very clearly, but the code example also uses the `@spec` annotator without describing it at all.

**Comment by Koziolek** [comment]
Look at #338 after finish with that I will add links to documentation lesson

**Comment by Koziolek** [comment]
I will add link in lesson :)

**Comment by Koziolek** [comment]
@scouten please close this if solution is OK :)
