### ISSUE TITLE
Section on mocking doesn't say why mocks are bad

### ISSUE THREAD

**Issue by scouten** [doomspork/elixir-school#593]
Why are they discouraged in the Elixir community, as referenced in http://elixirschool.com/lessons/basics/testing/#mocking?

(FWIW I'm no big fan of mocks myself, but I think this section would benefit from a description of the community's thought on mocks.)

**Comment by ybur-yug** [comment]
@souten [This goes into it a good bit](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/)

I can work on a writeup that doesnt just copypasta their work if its still open to be taken on.

**Comment by scouten** [comment]
@ybur-yug: great article, and it pretty much matches my own view on the subject. I'll be happy to review your writeup on it, though a link to that article would probably suffice.

**Comment by holsky** [comment]
@ybur-yug are you still on it? Otherwise I could give it a try in 1-2 paragraphs (plus a link maybe?)

**Comment by holsky** [comment]
Sorry for the messy timeline here, but the actual PR is only one commit.

**Comment by scouten** [comment]
@holsky I'm a bit confused. When I read the referenced commits (b846e9a, etc.), I see some new paragraphs that pretty reasonably address my question about mocking. But when I read PR #677, it appears you're adding a completely different section (about `assert_receive`) to the page. Maybe b846e9a was meant to be included in a different PR?

**Comment by holsky** [comment]
Hmm I'm not sure how that happened but it seems I accidentally overwrote my commit through a push-force. Now I have this commit cleanly on a separate branch in my fork: https://github.com/holsky/elixir-school/tree/improve_testing
Can I somehow update this pull request to use the other commit, or rather close it and create a new one?

**Comment by scouten** [comment]
@holsky you can't change the branch associated with a PR after creation, but I believe there is some git hackery you can do to straighten this out.

First: If you need to preserve the commit that is _currently_ associated with this PR, create a new branch that points to that commit (and, optionally, create a new PR for that new branch).

Then: Switch back to the `holsky:master` branch (i.e. the one associated with PR #677). Force that branch to the commit you cited in your `improve_testing` branch and force push that branch to your GitHub repo.

The end result of that should be that #677 again points to the new discussion on mocking.

Hope this helps!

**Comment by holsky** [comment]
thanks a lot, that should have worked :)

**Comment by holsky** [comment]
@doomspork This can be closed now I think, right? You usually create a new issue to manage the translations, correct? (If you reply yes I will do it)

**Comment by scouten** [comment]
+1 on closing

**Comment by doomspork** [comment]
Yes @holsky!  Thanks for the ping.
