### ISSUE TITLE
2 different meaning for 'pipe operator'

### ISSUE THREAD

**Issue by wolverineks** [doomspork/elixir-school#600]
the site calls 
```|``` [a pipe operator](https://github.com/doomspork/elixir-school/blob/master/lessons/basics/collections.md) and ```|>``` [a pipe operator](https://github.com/doomspork/elixir-school/blob/master/lessons/basics/pipe-operator.md)
i've heard ```|``` called cons operator or construction operator

is there a consensus on this?

**Comment by ybur-yug** [comment]
I have always heard of `|` as pipe operator w.r.t *nix, and `|>` as the pipe operator in Elixir. I always thought the operator in the language was met to resemble the name of the unix pipe because it is essentially performing the same function. I believe the unix piece is named after the character, which looks like a pipe.

Though this is purely anecdotal. If I have a few minutes I'll poke around for something official.

**Comment by brain-geek** [comment]
Looks like @wolverineks is right - `|` is not a pipe operator in Elixir and that's a mistake on our side.

[Learn you some erlang](http://learnyousomeerlang.com/syntax-in-functions) names it `cons operator`, so this looks like the term we should use:
```
The first function we'll write is head/1, acting exactly like erlang:hd/1 which takes a list as an argument and returns its first element. It'll be done with the help of the cons operator (|):
```

But I haven't found any info about this name in official Elixir docs/code - they only operate with term `cons cell` which is name of the [data structure](https://github.com/elixir-lang/elixir/blob/f3b44e551773247f9ef6f17ff7a4b86a21cf513d/lib/elixir/lib/list.ex#L18-L33).

**Comment by Slotos** [comment]
"|" is often called a pipe character. However in Elixir (or rather Erlang) it is a cons operator.

In (very) simple terms it doesn't split lists, it creates a link between a value and the rest of the list:

```elixir
iex(37)> [1 | [2 | [3 | [4]]]]
[1, 2, 3, 4]
```

List splitting uses it as following: list of *one element* followed by the rest equals a known list, what is that *one element*? Think of it as BEAM solving an equation for you. Another similar pattern looks like this:

```elixir
iex(33)> "this is " <> a = "this is Elixir"
"this is Elixir"
iex(34)> a
"Elixir"
```

**Comment by nscyclone** [comment]
The answer is given above and the fix process [has started](https://github.com/doomspork/elixir-school/issues/608). Shouldn't we close this issue?

**Comment by brain-geek** [comment]
You're right, @nscyclone
