### ISSUE TITLE
Chinese Translation: Basic Lessons

### ISSUE THREAD

**Issue by cizixs** [doomspork/elixir-school#61]
Hey, I want to translate this wonderful tutorial into Chinese, following is my progress right now.

- [x] index.md
- Basics
    - [X] basics.md
    - [X] collections.md
    - [X] enum.md
    - [X] pattern-matching.md
    - [X] control structures.md
    - [X] functions.md
    - [x] composition.md
    - [x] mix.md
    - [x] testing.md

**Comment by doomspork** [comment]
That's amazing @cizixs!  Let me know if there's anything you need help with.

**Comment by cizixs** [comment]
@doomspork The translation is going fine. Just a little confused how to do the PR:

1. send a PR after translating every chapter: basics, advanced and specifics
2. send a PR after translating all content into Chinese.

which one is recommended?

**Comment by doomspork** [comment]
Hi @cizixs, I'm open to whatever works best for you.  Personally I think it's easiest to do three separate PRs, one for basics, advanced, and specifics.

**Comment by doomspork** [comment]
Merged in #65
