### ISSUE TITLE
Exercises needed at the end of each lecture

### ISSUE THREAD

**Issue by ukchukx** [doomspork/elixir-school#619]
First off, I would want to commend the creator(s) of this awesome resource for a job well done.
I think if there are exercises at the end of each lecture, it would help deepen the understanding of the concepts taught.
Thanks again for this wonderful resource.

**Comment by ybur-yug** [comment]
I like the idea. Do you have any thoughts on exactly what they should cover or want to stab at opening a few PR's with examples in them to spark discussion further @ukchukx?

**Comment by setzer777** [comment]
Hi @ukchukx !

A few time ago we planned to do that and got into a really interesting debate [here](https://github.com/doomspork/elixir-school/issues/399)
The main idea is that some guys in the team doesn't think the best idea is to just add exercises at the end of the lessons, and they expose their opinions in the issue.

Why don't you take a look and then post your opinion on the topic? :)

**Comment by doomspork** [comment]
Thanks for @ukchukx, I'd love to hear your thoughts on #399.  

As part of the move from Jekyll to Phoenix that I'd like to complete, I'd like to add more interactive lessons.

**Comment by ukchukx** [comment]
Thanks for the correction, guys.
I didn't know there was an issue already addressing this, unfortunately (my half-hearted search did not turn up any).
> Do you have any thoughts on exactly what they should cover or want to stab at opening a few PR's with examples in them to spark discussion further 

Unfortunately not, @ybur-yug, as I'm just starting to learn Elixir.

That's a reasonable explanation, @setzer777. I'll take a look & post my opinion (if I have any & if no one has touched on it).

Kudos on the upcoming interactive lessons, @doomspork!

**Comment by doomspork** [comment]
This is definitely something we'd like to continue to pursue, conversation is continuing here #1310
