### ISSUE TITLE
False statement in OTP Supervisors/Task Supervisor/Supervised Tasks

### ISSUE THREAD

**Issue by X4lldux** [doomspork/elixir-school#658]
It states that if a task is supervised by `Task.Supervisor` and the task crashes, it will be restarted - it will not be! Default `:restart` spec in `Task.Supervisor` is set to `:temporary` which means that tasks will never be restarted.
By changing the example to:
```Elixir
import Supervisor.Spec

children = [
  supervisor(Task.Supervisor, [[name: ExampleApp.TaskSupervisor, restart: :transient]]),
]

{:ok, pid} = Supervisor.start_link(children, strategy: :one_for_one)
```
the statement would be true - but I suggest explaining the default behavior before that, for clarity.

**Comment by brain-geek** [comment]
I've digged into the [Elixir docs](http://elixir-lang.org/docs/stable/elixir/Supervisor.Spec.html) and looks like the default restart approach is `:permanent`:

```
worker(ExUnit.Runner, [], restart: :permanent)
By default, the function start_link is invoked on the given module. Overall, the default values for the options are:

[id: module,
 function: :start_link,
 restart: :permanent,
 shutdown: 5000,
 modules: [module]]
```

`Overall, the default values for the options are:` ` restart: :permanent`. 

But anyway, that's a good catch to ådd to lesson. Thanks, @X4lldux .

**Comment by X4lldux** [comment]
Cool for the idea! Even though it's just a side efetct ;)

But... Your showing docs for a regular Supervisor, while my issue is about Task.Supervisor, called `ExampleApp.TaskSupervisor` in the example, has it's [defaults](https://github.com/elixir-lang/elixir/blob/v1.3.4/lib/elixir/lib/task/supervisor.ex#L41) set to `:temporary`.

**Comment by brain-geek** [comment]
Wow, I didn't get that one. Fixed the PR.

Thanks, @X4lldux !

**Comment by X4lldux** [comment]
No problem. 
If you mean #716,  the update it self looks good, but you've missed the last paragraph - unless you want to have a separate PR with a bufix for that. :)

p.s.
sorry for mis-closing.

**Comment by doomspork** [comment]
@X4lldux is this good to close now that #716 merged?

**Comment by X4lldux** [comment]
Almost. The last paragraph still says:

> If our task crashes prematurely it will be **re-started for us**. This can be particularly useful when working with incoming connections or processing background work.

**Comment by doomspork** [comment]
Thanks @X4lldux!  @brain-geek do you want to fix this up too or should I?

**Comment by brain-geek** [comment]
Okay, but the funny thing here that in that case (`start_child`) it actually gets restarted.

Looks like `spawn_link` and `start_child` have [different](https://github.com/elixir-lang/elixir/blob/v1.3.4/lib/elixir/lib/task/supervisor.ex#L134-L137) defaults! :)

IEx example of trying the code from example:

```

iex(1)> import Supervisor.Spec
Supervisor.Spec
iex(3)> children = [
...(3)>   supervisor(Task.Supervisor, [[name: ExampleApp.TaskSupervisor, restart: :transient]]),
...(3)> ]
[{Task.Supervisor,
  {Task.Supervisor, :start_link,
   [[name: ExampleApp.TaskSupervisor, restart: :transient]]}, :permanent,
  :infinity, :supervisor, [Task.Supervisor]}]

iex(5)> {:ok, pid} = Supervisor.start_link(children, strategy: :one_for_one)
{:ok, #PID<0.88.0>}

iex(7)> {:ok, pid} = Task.Supervisor.start_child(ExampleApp.TaskSupervisor, fn -> 5/0 end)
{:ok, #PID<0.92.0>}

18:53:42.114 [error] Task #PID<0.92.0> started from #PID<0.80.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang./(5, 0)
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<20.52032458/0 in :erl_eval.expr/5>
    Args: []

18:53:42.118 [error] Task #PID<0.93.0> started from #PID<0.80.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang./(5, 0)
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<20.52032458/0 in :erl_eval.expr/5>
    Args: []

18:53:42.118 [error] Task #PID<0.94.0> started from #PID<0.80.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang./(5, 0)
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<20.52032458/0 in :erl_eval.expr/5>
    Args: []

18:53:42.118 [error] Task #PID<0.95.0> started from #PID<0.80.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang./(5, 0)
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<20.52032458/0 in :erl_eval.expr/5>
    Args: []
```

**Comment by brain-geek** [comment]
From the IEx output you can see that failed process gets started 5 times - and fails 5 times (then it hits the limit).

**Comment by brain-geek** [comment]
@X4lldux accounting that fact, do you think we can close this one?

We can add some more explanations, but I think that would be very confusing for beginners then.

**Comment by ybur-yug** [comment]
@brain-geek good catch, I think youre right about it being potentially very confusing to a beginner.

**Comment by doomspork** [comment]
@brain-geek nice work!  I think this safe to close this one for now, any notes will only confuse beginners and derail their learning.

**Comment by doomspork** [comment]
@X4lldux if you think we could improve this further please submit a PR and we can continue the conversation there 👍

**Comment by X4lldux** [comment]
@brain-geek I guess, in the scope of the example from the lesson, where the default restart policy is overridden to be `:transient` instead of `:temporary` your example is correct (in your example you also overrode default restart policy. But if you'd left `Task.Superviosr`'s default strategy, your _divdie_by_zero_ task would die once and never be restarted).

Maybe my initial proposition, adding `restart: :transient`, was a wrong one, cause it can confuse readers about the true intention of Task's and Task.Supervisor. But at least lesson is not stating false anymore! :+1:
