### ISSUE TITLE
Message Passing section in Advanced/Concurrency

### ISSUE THREAD

**Issue by ipmsteven** [doomspork/elixir-school#664]
In [Message Passing](https://elixirschool.com/lessons/advanced/concurrency/#message-passing) section, there is a code snippet which shows how process pass and listen message.

```elixir
defmodule Example do
  def listen do
    receive do
      {:ok, "hello"} -> IO.puts "World"
    end
  end
end

iex> pid = spawn(Example, :listen, [])
#PID<0.108.0>

iex> send pid, {:ok, "hello"}
World
{:ok, "hello"}

iex> send pid, :ok
:ok
```

This code is a little bit confusing for me since the new created process will exit right after it receive the first message(we can verify that by using `Process.alive?(pid)`) 

How about make a recursive call in `listen` so that it can keep receiving incoming messages?

```elixir
defmodule Example do
  def listen do
    receive do
      {:ok, "hello"} -> IO.puts "World"

      listen
    end
  end
end
```

**Comment by doomspork** [comment]
@ipmsteven I think is a great change!  Would you be interested in opening a PR with this change and perhaps a short note mentioning the recursion?

**Comment by ipmsteven** [comment]
sure
