### ISSUE TITLE
Advanced section, lesson 1 - Strings

### ISSUE THREAD

**Issue by viktorot** [doomspork/elixir-school#67]
The section says that Erlang strings are represented with single quotes. This is unfortunately incorrect. Strings in Erlang are represented with double quotes, the same as in Elixir.
 
As for single quotes, they are used to represent atoms that contain spaces, uppercase letters or any other characters that are "unconventional" for atoms. 

You can find the documentation for it [here](http://www.erlang.org/doc/reference_manual/data_types.html#id64703).

This part needs be updated.

**Comment by doomspork** [comment]
Thanks @viktorot, I'll open a PR with changes momentarily.  :grinning:
