### ISSUE TITLE
Add Documentation section

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#7]
Go over `@moduledoc` and `@doc`.

**Comment by doomspork** [comment]
This should also include `@doctest`

**Comment by pjhampton** [comment]
Hey doomspork.

Have you assigned anyone to this yet? If not, I would be keen to contribute.

pj

**Comment by doomspork** [comment]
@pjhampton that would be stellar, thank you.  

My initial plan was to cover `@moduledoc`, `@doc`, and `@doctest` but I'm open to suggestions.  If you'd like to discuss, you can ping me on Slack as `seanc`.

**Comment by doomspork** [comment]
Hi @pjhampton, still thinking of contributing this lesson?

**Comment by pjhampton** [comment]
Hey @doomspork. Hell yeah! Sorry, I have just been a bit busy with work and the holidays. I will have a draft by sometime early next week. Don't mean to hold this up!

I will just gist an **.md** so we can discuss the content, instead of a commit.

**Comment by doomspork** [comment]
That's great to hear @pjhampton.  Don't mean to rush you, just checking in. :grinning:

**Comment by pjhampton** [comment]
See this [gist](https://gist.github.com/pjhampton/ebe23982781418954741) @doomspork 

Still pretty raw, as I have only spent an hour on it so far. Still needs tidied up, proof read, etc. Some constructive feedback would be appreciated.

**Thoughts**

* We will leave doc testing to the Testing section, I will add that separately.
* We will add a *best practice* / * recap* section at the end.
* Talk about deploying to **hexdocs.pm**.
* Briefly Discuss using hexdoc without creating.

I tried to use Slack, but it seems like an exclusive club :-( Can't register. Sorry about that!!

**Comment by doomspork** [comment]
Hey @pjhampton, I'll look this over today and leave you my thoughts.  Thanks again for helping out.  Always excited to have new contributors!  :+1:

**Comment by doomspork** [comment]
@pjhampton it's looking good!  Thanks again for taking the initiative on this.

**Comment by pjhampton** [comment]
Ahh, all signed up now :+1: I'm @pjhampton as usual.

We'll connect soon. Let me just clean this up as it's still a bit of a grammatical nightmare!

**Comment by doomspork** [comment]
Closed by #74.  Thanks again @pjhampton :+1:
