### ISSUE TITLE
Using Github Projects in translation

### ISSUE THREAD

**Issue by devleoper** [doomspork/elixir-school#703]
Recently Github [released some cool features](https://github.com/universe-2016) that help collaboration: Reviewing and Project.

Previously when there is a improvements from English texts, we make an issue for translators to keep the translated lessons up-to-date. but it is hard for translators to organize _things to do_ and _things done_.

There are some good tools (e.g. [Trello](https://trello.com/)) to keep them up, but many of them are external services that require another sign-ups, invitations, installations, or URLs (that may make new translators feel confused).

Now we can create [projects](https://github.com/doomspork/elixir-school/projects) and place cards (cards can be imported from issues) to _To Do_ List instead of making checkboxes and mentioning.

Any ideas about this? This might change our workflow and let's discuss about that.

**Comment by devleoper** [comment]
Also, this may make not only translations easier, but Lessons suggestion(#50) more reachable and inspiring.

**Comment by ybur-yug** [comment]
I think would be awesome, and had been pondering about it myself but didn't come up with a robust solution as I usually just mark things to be translated...not actually do it at all, so I lack the perspective needed to make it easier for you folks to contribute in that form and/or even really outline or think about the process involved.

Basically, if you think its an awesome idea and wanna do it, I am 10,000% for it and will happily follow whatever guidelines that are set up @devleoper 

I imagine it basically could boil down to an addition to `CONTRIBUTING.md` once it is discussed and process/flow agreed upon by the people whom it affects the most.

But yeah, 💯 👍 from me.

**Comment by ybur-yug** [comment]
PS as I ponder more overall i think a LOT of the new features GH has launched could really help us here. Maybe we should start another big group thread just to talk about potential directions w.r.t managing the project and leveraging these. It has grown so much that the sheer amount of contribution is even growing compared to when I came on around July and I'm sure we could come up with some things that would make all of our lives easier and help make this even more awesome.

CC @doomspork

**Comment by doomspork** [comment]
@devleoper and @ybur-yug, I think Projects is a _great_ solution for managing translations and new lessons.  I'm all for giving it a go.

**Comment by doomspork** [comment]
@devleoper / @ybur-yug — I created two Projects: Translations and New Lessons.  What next?  What columns do we need?  Suggestions, In-Progress, Done?

**Comment by doomspork** [comment]
@nscyclone / @pjhampton / @Koziolek / @brain-geek or any other contributors / translators want to weigh in?

**Comment by pjhampton** [comment]
I think this is a great idea 👍  What about an **Updating Lessons** project?

**Comment by ybur-yug** [comment]
@doomspork I've always liked having like 'ideabox' (all ideas/thoughts, catch-all), 'backlog' (planned to be implemented), 'in progress', and 'done' for the new-content style stuff. For translation I think the 'ideabox' doesnt really fit.

**Comment by nscyclone** [comment]
I suppose @ybur-yug's suggestion looks good but I'd use `backlog`, `wip` & `done` as columns and create a new separate `ideabox` project with same columns just because ideas should not be limited to lessons and translations only and as was mentioned earlier it doesn't fit for translations.

**Comment by brain-geek** [comment]
This idea sounds awesome. 👍

**Comment by Koziolek** [comment]
Sounds good  :+1:

**Comment by doomspork** [comment]
I've added a third project per @nscyclone suggestion: `Ideabox`.  I've also created the initial columns: `backlog`, `wip`, and `done`.

Would anyone be interested in helping me migrate over the existing issues in cards?

**Comment by brain-geek** [comment]
Hey, @doomspork , one more idea: we may ocasionaly need 'fix/change' tasks in projects.

One example would be my current 'spellcheck all the lessons' task. 

Or issues with requests like #594 , #585 or other, which require lesson updates. When this improvement is done in English - task in 'Translations' will be created.

**Comment by ybur-yug** [comment]
@doomspork it seems we have this working reasonably well with the new projects setup. Should we close this?

**Comment by doomspork** [comment]
@brain-geek very good point, where do you think those should live?

@ybur-yug yeah, we can close this and finish up any conversations 👍

**Comment by brain-geek** [comment]
@doomspork I guess that should be third project.
