### ISSUE TITLE
Translation version control

### ISSUE THREAD

**Issue by cizixs** [doomspork/elixir-school#71]
Right now I am translating into tutorial into Chinese, and find out a issue: **How to keep translation up to date?**

There are updates on previous lessons, which makes my translation out of date. The obvious way to solve this is to go through commit logs and find out the updated content, then add another patch.

Do you guys have a better way to work on this one?

**Comment by doomspork** [comment]
@cizixs this is a great question!  I don't have a good solution so I'm open to any suggestions you have.  So far I've been trying to keep up with changes in #49 for @3100 but I don't know if that's working out well.

As the folks handling the translations, what would make it easiest on you?

ping @milmazz, @erickgnavar, @3100

**Comment by milmazz** [comment]
@doomspork I think it's really hard to keep synchronized all the content, for example, in some translations of the official pages about [Debian](https://www.debian.org/) they offer a note that says something like:

> Note: The original document (link to the original document in English) is newer than this translation. 

So, with this in mind, we can set a new variable in the frontmatter, let's say `version` and the link to the original document in English, if both versions differ then we put the note in the translated content.

By the way, I used [Transifex](https://www.transifex.com/) a long time ago in other open source projects, looking at their page they now offer something called *Transifex Live*, and in this [section](https://www.transifex.com/pricing/), they said that they support open source projects for free in their new pricing schema.

**Comment by doomspork** [comment]
I like the idea of adding a note to the translated versions.  Great suggestion @milmazz.

I'll take a look at Transifex later this week.

**Comment by doomspork** [comment]
@milmazz do you recall which other OSS projects used Transifex?  I want to see how other people are using it.

**Comment by milmazz** [comment]
@doomspork Right now I recall [Django](https://www.transifex.com/django/django/) and [Turpial](https://github.com/satanas/Turpial) (a Twitter client written in Python). But both projects use Transifex to offer translations for their source code base, not for their sites. Maybe we need to find better examples for our use case.

**Comment by doomspork** [comment]
I think our current approach with GitHub issues is working.  We can investigate an alternative service/product/solution if we continue to grow and feel pains keeping synced.

Thanks for all the help guys! :+1:
