### ISSUE TITLE
Is ruby 2.3.0 required

### ISSUE THREAD

**Issue by et** [doomspork/elixir-school#739]
The latest stable release of ruby is `2.3.1` yet the `Gemfile` indicates that you must use [2.3.0](https://github.com/doomspork/elixir-school/blob/master/Gemfile#L2).
Can that be changed to `~> 2.3.0` so `2.3.1` can be used to run the Jekyll app?

**Comment by doomspork** [comment]
I think that should work @et, would you mind opening a PR?

**Comment by et** [comment]
#741
