### ISSUE TITLE
Improve Elixir School's SEO

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-school#75]
Not my area of expertise.  Going to use this issue as a place to gather information and plan out a strategy.

**Comment by pjhampton** [comment]
It doesn't seem like there is much on Jekyll SEO from the [Jekyll Blog](http://jekyll.tips/tutorials/seo/), just a couple of tips. What has been done and not from this post with Elixir School?

**Comment by doomspork** [comment]
I have done _nothing_ towards SEO.  I just noticed that Googling for different Elixir resources didn't return Elixir School for many searches.

**Comment by pjhampton** [comment]
It seems like a good idea. 

How do we measure this though? Some would argue SEO is never *really* done, and is more of a rolling effort. Maybe I could compile a list of tasks based on some research and work from there?

**Comment by doomspork** [comment]
@pjhampton I haven't really thought about how to measure this _yet_.  Right now there is no SEO and there should be some.  Googling for Elixir resources should return Elixir School.

I reached out to some former colleagues who work in SEO.  I'll update the issue as I get more information from them.

**Comment by doomspork** [comment]
After a bit of thought I came up with a simple milestone:

+ Elixir School should be on the first page of any Elixir resource, learning material, or tutorial search.

How does that sound?  The plan would be to work incrementally towards that goal.

Two tools that were recommended to me:

+ https://en.onpage.org/
+ https://moz.com/tools/seo-toolbar

**Comment by doomspork** [comment]
I'm going to close this now that the ball is rolling.   I think we all know SEO is a never-ending :grinning:
