### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by firec0der** [doomspork/elixir-school#771]
Hi, folks!

Looks like someone started translating lessons to Ukrainian. Is here someone in charge of it?
If no, I can do it.

**Comment by doomspork** [comment]
Howdy @firec0der!  @brain-geek is heading up the RU and UA, I'm sure he'd welcome your help!

**Comment by brain-geek** [comment]
Hey @firec0der .

Yes, I've started translating ukrainian. Do you want to take a lesson for translation?

**Comment by firec0der** [comment]
Hi, @brain-geek.
Yeah, I'd like to help.

**Comment by brain-geek** [comment]
I've created the task #772 to track the progress of Ukrainian translations.

Process is simple: you chose the topic/article from the non-taken ones and translate it. One translated article - one PR.

@firec0der if you need any more help - ping me on Slack or email or even here. I'd love to help.

**Comment by doomspork** [comment]
I'm going to close this since we have #772 now.  Thanks for joining the efforts @firec0der!

**Comment by firec0der** [comment]
Thank you guys. Let the challenge begin! :)
