### ISSUE TITLE
Behaviours lesson improperly numbered on list of advanced topics

### ISSUE THREAD

**Issue by ybur-yug** [doomspork/elixir-school#775]
![example](http://i.imgur.com/CJuOUtO.png)

I merged this one and didn't realize the error in how its added to advanced. I can fix this one tomorrow if someone else isn't around to hotfix it this evening.

**Comment by doomspork** [comment]
Should be fixed by https://github.com/doomspork/elixir-school/commit/99e5e06443dbecc68ac0e0bf4d13a9e7e3060b4c.  It's deploying now.

**Comment by ybur-yug** [comment]
@doomspork PR'd one other small issue with this in #776
