### ISSUE TITLE
Add Style Guide.

### ISSUE THREAD

**Issue by pjhampton** [doomspork/elixir-school#79]
It seems that the number of contributors of this project is growing. In my opinion it would be good to have a *rough style guide* in which all authors should work to. This is drawn from my experience with the documentation lesson. Examples could include:

- Omit IEx numbers. 

```
iex(1)> # bad
iex> # good
```

- Using `$` to denote terminal prompt

```
$ man cd # etc etc
```

This could be added as a separate file, to the contributor file, or even to the README depending on how concise it is.

What do you guys think about this?

**Comment by milmazz** [comment]
@pjhampton I think this is a great idea, but, I think this style guide should be explained in the `CONTRIBUTING.md` file instead of the `README.md`.

**Comment by doomspork** [comment]
This is a great idea @pjhampton :+1: 

Don't forget the Wiki if that's easier than a file under version control.  We could consider moving the translation guy to the Wiki as well.

**Comment by pjhampton** [comment]
Ok, cool! I will take this on during the weekend. I think we will put it in the wiki to begin with, and depending on how it is going to be, maybe we can move it?

**Comment by doomspork** [comment]
That sounds good to me @pjhampton.  Let me know if there's anything I can help with.

**Comment by pjhampton** [comment]
Thanks @doomspork! Maybe I spoke too soon on the Style Guide implementation. 

I decided to focus on completing the Sigils lesson first which will I aim to create a pull request in the 48 hours. After that I will get back to the SG activities.

**Comment by doomspork** [comment]
All good in the hood.  Just making myself available to help :grinning:

**Comment by doomspork** [comment]
I had some downtime today so I started on this, let me know your thoughts: https://github.com/doomspork/elixir-school/wiki/Lesson-Styleguide.

Feel free to make changes.  We can use this issue to discuss proposed styles, sound good?

**Comment by doomspork** [comment]
Once we get an initial version nailed down let's not forget to link from the README and CONTRIBUTIING.md.

**Comment by pjhampton** [comment]
This looks really swell @doomspork, thanks! I will add some stuff later on.

**Comment by doomspork** [comment]
I'm going to close this issue since we have the styleguide in place.
