### ISSUE TITLE
Permission to use material and brand for a workshop

### ISSUE THREAD

**Issue by imranismail** [doomspork/elixir-school#794]
We are organizing a workshop to raise some awareness around Elixir, it's not going to be monetized but there will be some amount of "commitment fee" that the attendants need to pay. Something around $5 usd.

We will be keeping it true to ElixirSchool and brand it as ElixirSchool Kuala Lumpur.. Kuala Lumpur being the city.

The idea is to mimic the ruby community's Ruby Girl's movement.

**Comment by ybur-yug** [comment]
@doomspork is the owner and only person who can comment on if that is truly fair game.

@imranismail IMHO any beginner event shouldn't have a pay-wall for entry, its just silly. The point of these materials are to give _everyone_ a _free_ resource; and that doesn't accomplish that goal at all. But I'm not the owner/creator so my opinion is just that, some random guy's opinion.

**Comment by imranismail** [comment]
@ybur-yug it's not a paywall really, just a commitment fee because of the limited slots available. I've held past Elixir events that are free but those are more on talks instead of workshop style.

**Comment by doomspork** [comment]
Hi @imranismail!  I'm excited to hear you're interested in making in-person training available to people in your area.  I am more than happy to have you make use of the materials, but I must say I am not a fan of branding this an "Elixir School" organized a event when it is not at all affiliated with us.

If you were actively involved in Elixir School through translations or contributions I think I might feel a bit differently, but right now this kind of comes off as someone looking to benefit from the hard work of other people and I can't get onboard with that.

If you'd like to chat about this more, feel free to ping me on Elixir Slack @ `seanc`.

**Comment by imranismail** [comment]
I've talked to @doomspork and resolved to branding it something differently.

For those interested, the small community is here: https://www.facebook.com/groups/elixirmy/

I'll update this issue once we've set up the event.

Thank you!
