### ISSUE TITLE
Issues with Plug lesson

### ISSUE THREAD

**Issue by moxley** [doomspork/elixir-school#828]
Hi, thank you for contributing to the Elixir ecosystem with Elixir School!

I landed on Elixir School while searching for a quick example to get a minimum Plug application running. My application only needs to expose a single JSON endpoint for an AJAX request.

Can I make a pull request with the following changes?

* Move `VerifyRequest` example down to a later section. It's not essential to get something up and running.
* Move `port` configuration down to a later section. It's not essential to get something up and running.
* Is having a router strictly necessary for getting something working with Plug? If there isn't, it can be moved down to a later section as well.
* Include the `mix deps.get` command needed to pull in dependencies. Novice Elixir developers are likely to miss this. Even an experienced Elixir developer may not catch this.
* There are two different versions of `def applications`. Only the final version is necessary.
* Remove `import Plug.Conn` from verify_request.ex file, line 2. It's unused, causing a compile warning.

**Comment by ybur-yug** [comment]
Any and all pull requests are welcome!

I'd recommend checking out our [style guide](https://github.com/doomspork/elixir-school/wiki/Lesson-Styleguide) to avoid any little nitpicks that can be common/easy to make if you arent familiar with the patterns.

Point per my, my general thoughts:

1. I think the goal of a specifics lesson is a bit more akin to something we'd see out in the wild, and this mimics that. I dont have strong feelings about it, but I do think it fits personally. It looks like @doomspork wrote this bit so it would probably be best to speak with him per that part.

2. I have no strong feelings on this part, and lack the eyes of a beginner. So I'd fall on your side here if it helps to strip it.

3. I'm tired and dont have an answer to that one off the top of my head. Will update in and edit later.

4. This is definitely a mistake

5. Sounds like another mistake

6. Good catch, thank you, another mistake there too it seems

I want to verify these running through on my own and will when I have time and then anyone else who wants to chime in can add to the discussion here too, if that works.

Thanks!
