### ISSUE TITLE
Routing/Naming Mismatch In Libraries Section

### ISSUE THREAD

**Issue by ybur-yug** [doomspork/elixir-school#831]
This may be intentional. If it is and I missed the conversation in the PR for adding the libraries section, apologies.

If we go to look at [the new Guardian Lesson](http://elixirschool.com/lessons/specifics/guardian/) the URL is `/lessons/specifics/guardian` but its listed under the `Libraries` entity which is listed with pieces that all have their own namespaced routes.

I would think that Libraries lessons would fall into `libraries/my_lesson`, just for the sake of good routing. But if its some limitation of jekyll that makes sense, too.

**Comment by doomspork** [comment]
@ybur-yug this is a mistake.  We should create the directory and move the lessons.

**Comment by ybur-yug** [comment]
closing per #832 assuming it will end up proper
