### ISSUE TITLE
Plug, Ecto and Mnesia should be in Libraries section

### ISSUE THREAD

**Issue by ybur-yug** [doomspork/elixir-school#851]
I think these don't fit in specifics as they are libraries. Therefore it would make more sense to put them there. If anyone is opposed to this please chime in, otherwise I will PR it later today or this weekend.

**Comment by agustif** [comment]
Hey, I'm no expert but would enjoy collaborating on Ecto at least (the lib I know more of the three)

What did you had in mind?

**Comment by doomspork** [comment]
I don't agree,  I see Libraries being for anything not part of Elixir-lang (Plug, Ecto) or OTP/Erlang (Mnesia).

Happy to hear what other's say though.  Thoughts @brain-geek, @nscyclone, @pjhampton, or anyone else?

**Comment by pjhampton** [comment]
Emm, I agree with @doomspork. They are part of either the Elixir ecosystem (so to speak) or OTP, therefore specifics. If they were written by a 3rd party, I would see your point.

**Comment by ybur-yug** [comment]
That does make sense. I hadn't thought of it from an ecosystem-level. I'll close this.
