### ISSUE TITLE
Rearrange 'Basic' lessons

### ISSUE THREAD

**Issue by pjhampton** [doomspork/elixir-school#86]
It it possible we could rearrange the lessons from:
```
...
9. Testing
10. Documentation
11. Sigils
```
to
```
...
9. Sigils
10. Documentation
11. Testing
```

This is so it logically flows better when talking about doc testing (which doesn't exist yet, I believe). I wanted to bring this up here first just incase it breaks anyones workflow.

**Comment by doomspork** [comment]
Sure!  Feel free to open a PR with them re-org for review :grinning:

**Comment by pjhampton** [comment]
Cool stuff @doomspork! Reworked in PR #85.
