### ISSUE TITLE
Portuguese Translation: Basic Lessons 🇧🇷

### ISSUE THREAD

**Issue by tiagobarreto** [doomspork/elixir-school#89]
- [x] index.md
- Basics
 - [x]  basics.md
 - [x]  collections.md
 - [x]  enum.md
 - [x]  pattern-matching.md
 - [x]  control structures.md
 - [x] pipe-operator.md
 - [x]  functions.md
 - [x]  composition.md
 - [x]  mix.md
 - [x]  sigils.md
 - [x]  documentation.md
 - [x]  testing.md

**Comment by pragmaticivan** [comment]
Update this?

**Comment by doomspork** [comment]
@pragmaticivan if you're interested in continuing your contributions, I'd be glad to add you to the repo so you can help with these things.  Only request is that big changes go through PR so there's an opportunity for comment (24-48 hours).  Thanks again!

**Comment by doomspork** [comment]
Updated :+1:

**Comment by pragmaticivan** [comment]
I do have plans in continuing my contributions.

**Comment by doomspork** [comment]
Great, I will add you now.  Thank so much @pragmaticivan :grinning:

**Comment by pragmaticivan** [comment]
Just for tracking, I'm working on testing.md. The last basic one.

**Comment by pragmaticivan** [comment]
Basic is ready :D Can you tweet about the basic section in Portuguese @doomspork Would like to attract more Brazilians to contribute to this project.

**Comment by doomspork** [comment]
@pragmaticivan I will do that shortly!  Thanks @pragmaticivan

**Comment by pragmaticivan** [comment]
WIP: pipe-operator.md (@pragmaticivan)

**Comment by pragmaticivan** [comment]
The last one is in #126 .

**Comment by pragmaticivan** [comment]
Close this one as well? @doomspork

**Comment by doomspork** [comment]
:+1:
