### ISSUE TITLE
Missing content in Spanish Translation

### ISSUE THREAD

**Issue by tiagobarreto** [doomspork/elixir-school#91]
Some topics are not translated. 

- Básico
  - [ ] Comparación {Missing content}
- Coincidencia de Patrones
  - [ ] Operador Pin {Update content}

**Comment by erickgnavar** [comment]
Fixes in [#160](https://github.com/doomspork/elixir-school/pull/160)

**Comment by tiagobarreto** [comment]
Thanks @erickgnavar! :+1:
