### ISSUE TITLE
Remove GenEvent From OTP Concurrency Lesson

### ISSUE THREAD

**Issue by ybur-yug** [doomspork/elixir-school#939]
The long term plan is to [deprecate GenEvent](http://blog.plataformatec.com.br/2016/11/replacing-genevent-by-a-supervisor-genserver/).
We currently go into it [here](http://elixirschool.com/lessons/advanced/otp-concurrency/#genevent).

Since we have shown a good bit of concern with regard to what we should encourage as patterns and practices, we should probably remove this section of the lesson and expand on the GenServer bit.

I would be happy to take this on if its decided to be a change we should do.

CC @doomspork @nscyclone @brain-geek @Koziolek @devleoper and anyone else who might have an opinion.

**Comment by Koziolek** [comment]
It is part of bigger job. Updating content to Elixir 1.4.

**Comment by doomspork** [comment]
Closing this since we've got #908
