### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by gemantzu** [doomspork/elixir-school#944]
I think it is time to add some versioning in these translations, so we can see right away which files need editing. We can add an integer on the `header` of the file (right below language for example) that gets bumped up every time a change is submitted.  This has to work only on the english version.  The translations have to declare which version of the original file they cover.
This way, I think we can also show in the website that a translation is `deprecated` and needs some help to stay updated. 
What do u guys think?

**Comment by doomspork** [comment]
@gemantzu I think this is a great idea.  Any suggestions on how best to tackle this?

CC @nscyclone @brain-geek @devleoper @Koziolek and friends?

**Comment by Koziolek** [comment]
Absolutely yes. Versioning is great, but that deprecated is brilliant idea :)

**Comment by gemantzu** [comment]
We could always add versioning like we do in our software (major_version.minor_version.bug_fix) or a simple integer like 100, it becomes 110 if there are some big changes and 111 in minor tweaks. 200 if someone does a major overhaul.  The status becomes `deprecated` when the major version is different, `needs updates` when the second number is different and nothing when the last number is different. This number gets added below the lang in the header.

**Comment by doomspork** [comment]
So as a plan of attack @gemantzu, what all do we need to do?  I'm guessing something along the lines:

1) Add a `version: x.x.x` to the Jekyll metadata.  
2) Tag the current English lessons as `v1.0.0` and then update all translations to their appropriate version.  Those not current could be something like `v0.1.0`.
3) Add some script to compare the current version with the English version and label it accordingly

**Comment by gemantzu** [comment]
1. Sure
2. Tag the current version as 1.0.0 and deprecate all translations, so that maintainers can bump up the versions depending on if the translation file is updated or not.
3. I don't have the slightest idea about Jeckyl, but can we have a script to do that each time there is a change?

**Comment by doomspork** [comment]
@gemantzu I believe since Jekyll has to be recompiled and generated each time that we can hook into that for the checks.  I'll spend some time this weekend looking into it.

**Comment by devleoper** [comment]
If we version documents like vx.x.x, we can display message depending on the differences of versions. Such as:

- There are small changes since this document was translated.
- There are changes since this document was translated. Some parts might not work.
- There was big changes since this document was translated. Most of the parts might be outdated and not working.

**Comment by gemantzu** [comment]
@devleoper I like your messages, we should go with those.  
Could we also do a report for the translators? That will categorize the lessons by the magnitude of differences? 
example:
## Major Changes
### Basics - Enum
### Advanced - Concurrency
## Minor Changes
### Specifics - Plug
### Libraries - Poolboy
## Bugfixes
### Specifics - Ecto
This could show in the website, or just be a plain text file inside the root translation folder.
I will start looking at jeckyll so i can help more.

**Comment by brain-geek** [comment]
This is a great idea, I vote for implementing this.

**Comment by doomspork** [comment]
I've been thinking about this more today.  Could we do something with this to handle missing lessons and encourage folks to contribute those?

**Comment by gemantzu** [comment]
I've been thinking about this as well but chores and other matters got the best of me. I will try some things tomorrow. One: write a script that will add the initial version on the first line (1.0.0 for english, 0.9.0 for all others). Two: write a script that we have to find a way to run every time we build with jekyll (does jekyll have a way to support this?). This script will build an `index` of the english files per category, and every available translation and make an .md file for each language as a status report. I'm too tired to try anything now, so let's see what we have tomorrow.

**Comment by doomspork** [comment]
I started working on this last night using Jekyll plugins and have made promising progress.  I'll try to get things cleaned-up tonight so I can open a PR to further the conversation.  Hope everyone is having an enjoyable weekend 😁

**Comment by gemantzu** [comment]
I have all files ready (I used an elixir script to open all files and add the line on the top). Do u want to create a branch so we can check all things out before we merge to master?

**Comment by doomspork** [comment]
@gemantzu that's great!  I'll push up my branch here in a little bit, it's not 100% done yet 👍

**Comment by gemantzu** [comment]
Sure, so I can send a PR on the branch instead of master!

**Comment by doomspork** [comment]
@gemantzu I've opened a PR with my changes @ https://github.com/doomspork/elixir-school/pull/961

I'd love to get people's feedback on the approach.  For now this just handles calculating the `en` versions and then comparing every subsequent page and adding a warning.  For now the warning is very basic, we'll style it up once folks are happy.

![image](https://cloud.githubusercontent.com/assets/73386/22904291/1f344340-f1f9-11e6-9178-bde7f50ebcad.png)

**Comment by nscyclone** [comment]
Congratulations, the versioning is now [live](http://elixirschool.com/pl/lessons/basics/pattern-matching/)! :tada: Huge thanks to everyone for making this happen!

@doomspork, should this issue be closed?

**Comment by doomspork** [comment]
Yes @nscyclone!

Thanks again everyone 👍
