### ISSUE TITLE
Moving through lessons at bottom of page

### ISSUE THREAD

**Issue by KaoruDev** [doomspork/elixir-school#95]
In mobile view it's frustrating to scroll all the way back to the top to get to the next or prev lesson, would be awesome to have links at the bottom of the page to continue the lesson.

**Comment by doomspork** [comment]
Hi @KaoruDev, are you referring to Previous and Next links?

**Comment by KaoruDev** [comment]
yep!

**Comment by doomspork** [comment]
Good suggestion!  I'll take a look at how others have accomplished this in Jekyll.

**Comment by doomspork** [comment]
@KaoruDev would you like to try tackling this?  If not, I think we'll close this for the time being.

**Comment by KaoruDev** [comment]
I'll try to take a stab at it, if i don't get it done by Monday, close this =)

**Comment by doomspork** [comment]
Thank you 👍
