### ISSUE TITLE
Better mobile menu

### ISSUE THREAD

**Issue by KaoruDev** [doomspork/elixir-school#96]
![image](https://cloud.githubusercontent.com/assets/5273755/13156753/e3229d48-d638-11e5-9d33-f1a09c86bf36.png)

it's frustrating to be viewing this on a phone and see the massive navbar take up the entire page.

would be nice to have a slide menu ( responsive only )

https://codyhouse.co/gem/3d-bold-navigation/
might be cool.

**Comment by doomspork** [comment]
Closing this for now.  We've collapsed the Advanced and Specific sections by default and added additional styles to make the links easier to see.
