### ISSUE TITLE
Plug Router.start/2 is undefined or private

### ISSUE THREAD

**Issue by xinz** [doomspork/elixir-school#965]
Hi,

Thanks for this website for my learning, I refer the Plug specifics https://elixirschool.com/lessons/specifics/plug/ , when setup the following code

#lib/example/router.ex
```
defmodule Example.Router do
  use Plug.Router
  plug :match
  plug :dispatch

  get "/", do: send_resp(conn, 200, "Welcome")
  match _, do: send_resp(conn, 404, "Oops!")
end
```

and 

#mix.exs
```
def application do
  [
    applications: [:cowboy, :logger, :plug],
    mod: {Example.Router, []}
  ]
end
```

I restart the server with `mix run --no-halt`, I got the following error message 

> ** (Mix) Could not start application plugtest: exited in: Example.Router.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Example.Router.start/2 is undefined or private
            (plugtest) Example.Router.start(:normal, [])
            (kernel) application_master.erl:273: :application_master.start_it_old/4

I check the Plug router source code, there's no start/2 function defined, and find the following way to invoke

`The router is itself a plug, which means it can be invoked as:
      AppRouter.call(conn, AppRouter.init([]))`

Is anyone could help me to advise on this issue? Thanks in advance.

Here is the dependency tree version, Elixir 1.3.3, Erlang/OTP 19 [erts-8.0.2]
├── cowboy ~> 1.0.0 (Hex package)
│   ├── cowlib ~> 1.0.0 (Hex package)
│   └── ranch ~> 1.0 (Hex package)
└── plug ~> 1.0 (Hex package)
    ├── cowboy ~> 1.0.1 or ~> 1.1 (Hex package)
    └── mime ~> 1.0 (Hex package)

**Comment by xinz** [comment]
Looks like this section of Plug document has typo, the original tutorial of Plug.Router section as below:

`
def application do
  [
    applications: [:cowboy, :logger, :plug],
    mod: {Example.Router, []}
  ]
end
`

My resolution it keep the mix.exs as:

`
def application do
  [
    applications: [:cowboy, :logger, :plug],
    mod: {Example, []}
  ]
end
` 

And modify the lib/exmaple.ex, the original code as 
`  
def start(_type, _args) do
    children = [
      Plug.Adapters.Cowboy.child_spec(:http, Example.HelloWorldPlug, [], port: 8080)
    ]
    Logger.info "Started application"
    Supervisor.start_link(children, strategy: :one_for_one)
  end
`

After update:
`
def start(_type, _args) do
    children = [
      Plug.Adapters.Cowboy.child_spec(:http, Example.Router, [], port: 8080)
    ]
    Logger.info "Started application"
    Supervisor.start_link(children, strategy: :one_for_one)
end
`
child_spec with `Example.Router` will make the Router start, hope this comment can help for your study.

**Comment by doomspork** [comment]
@xinz if you'd like to submit a PR to fix the lesson that would be greatly appreciated!

**Comment by xinz** [comment]
@doomspork , sure, it's my pleasure, please review my submit https://github.com/doomspork/elixir-school/pull/967
