### ISSUE TITLE
Be able to see Diff

### ISSUE THREAD

**Issue by KaoruDev** [doomspork/elixir-school#97]
![image](https://cloud.githubusercontent.com/assets/5273755/13156848/6e51a0a8-d639-11e5-817d-64060dff2e36.png)

I'm not even sure how this would work, but it would be nice to highlight the diff in between code:

![image](https://cloud.githubusercontent.com/assets/5273755/13156874/93e22c02-d639-11e5-9020-4e53300ef87f.png)

or even maybe an arrow that points to what is different in the code.

**Comment by doomspork** [comment]
@KaoruDev this could be a very helpful addition.  Would you be interested in researching some options for how we might best achieve this?

**Comment by KaoruDev** [comment]
i have it on my to do list, but if someone else picks it up that's cool too

**Comment by doomspork** [comment]
Thanks :+1:

**Comment by doomspork** [comment]
I'm going to close this for now, I don't think this is something we can feasible support at the moment.
